#sdk: "/Users/robgalvin/.rvm/gems/ruby-1.9.3-p194/gems/rhodes-4.0.0.beta.59"
sdkversion: "4.0.0"
name: "RhoEmber"
version: 1.0
vendor: "rhomobile"
build: "debug"
bbver: 6.0
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphoneos7.1"
#sdk: "iphonesimulator7.1"
  provisionprofile: 
  codesignidentity: "iPhone Distribution: Fish Room Inc"
  entitlements: 
  BundleIdentifier: "com.rhomobile.playbook"
  BundleURLScheme: "playbook"
  emulatortarget: "ipad"
wp:
  productid: "5df3b720-f93a-0130-39a6-3c07547b3491"
symbian:
  uid: "0xe41a2db0"
android:
  version: "2.3.3"
  capabilities:
    - hardware_acceleration
app_type: "rhoelements"
extensions:
  - rhoconnect-client
capabilities:
  - camera
motorola_license: "`VLDr@le`9k:aCtlP$1@@PQdWnqF7y/gvj0L`SRm`Yt6j=EUb(F?a;7vLTl5fdkFS(c:rsjH@G1Zadt@`hnMPj1UW,V$d:i|2,0m2tg`Iy5jX|7PnegFJyoQd-o|qsVObHOZ;E;o"
